### ISSUE TITLE
Signed releases

### ISSUE THREAD

**Issue by xloem** [connectordb/connectordb#314]
It's incredible to see that the commits to this project are cryptographically signed.

Unfortunately, the releases are not yet.

Please distribute signatures with your releases.  See for example https://wiki.debian.org/Creating%20signed%20GitHub%20releases .

**Comment by dkumor** [comment]
Yep! The last release was quite a bit ago, and was before setting up PGP for the project. Future releases (including the upcoming 0.3.0b1 will all be cryptographically signed, and even optionally distributed through the keybase filesystem.

**Comment by xloem** [comment]
That's great!
