### ISSUE TITLE
Accept donations

### ISSUE THREAD

**Issue by xloem** [connectordb/connectordb#315]
It would be nice to be able to donate financially to the project.

[BitHub](https://github.com/WhisperSystems/BitHub) is one way to allow this.

**Comment by dkumor** [comment]
I was actually looking for something like this - I'll look at the code, and see it it can be adapted to work with ConnectorDB. Thanks!

**Comment by dkumor** [comment]
Option to donate bitcoin added to dev website https://dev.connectordb.io/ (website will go live on release of new version). It doesn't use BitHub yet. For now, I have created a special BTC address for the project.
