### ISSUE TITLE
When building from source, the UI bundle*.js files do not get generated and installed automatically

### ISSUE THREAD

**Issue by proffalken** [connectordb/connectordb#321]
Building from git on a [Pine64](http://pin64.org)

Ran `make deps`, `make` and `npm run build` in the app directory however the bundle.js files do not appear to have been created.

Copying them from the latest alpha release "fixed" the solution, however the docs may need updating to fix this properly.

**Comment by dkumor** [comment]
Can you paste the output of the make command?

**Comment by proffalken** [comment]
I'll have to re-run it tonight or this weekend to get that, but I'll do it as soon as I can.

**Comment by dkumor** [comment]
I was unable to reproduce this issue. `npm run build` in the `app` directory creates a `bundle.js` - I tested both on linux and mac, and it successfully works in CI also. Are there any error messages that show up?

**Comment by dkumor** [comment]
No response, closing.
