### ISSUE TITLE
Load Testing

### ISSUE THREAD

**Issue by josephlewis42** [connectordb/connectordb#55]
We need a benchmark for our backend services through the REST API.

What we know
- Etsy is happy with ~200ms queries on their website
- RTT to the connectordb.com is roughly 53ms
- Pulling the AskReddit homepage json takes roughly .8 seconds
- [3G latency is roughly 300ms](https://github.com/tylertreat/Comcast)
- [Various other latencies](https://gist.github.com/jboner/2841832)

What we want:
- 10000 users on our service
- Each user has 5 devices and ten streams each submitting a point every 30 seconds (16000/sec)
- Every REST query goes through the system within 200ms (plus RTT)
- 20% of our userbase is doing queries at any one time
- The length of a data query is 1 month of data (we may want to set a hard limit on this to avoid DOS attacks)

**Comment by dkumor** [comment]
Not currently a priority.
